# Generated by Django 4.2 on 2023-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hosting", "0003_alter_booking_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["room", "begin"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="amount",
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
